package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// APIKey mirrors a row in the api_keys table.
type APIKey struct {
	ID           string
	KeyHash      string
	KeyPrefix    string
	OrgID        string
	Name         string
	Scopes       []string
	RateLimitRPM int
	RateLimitTPM int
	IsActive     bool
	CreatedAt    time.Time
	ExpiresAt    *time.Time
	LastUsedAt   *time.Time
}

// NewKey carries the parameters needed to mint a new API key. The
// plaintext key itself is generated by the caller; this struct does not
// hold it.
type NewKey struct {
	OrgID        string
	Name         string
	RateLimitRPM int
	RateLimitTPM int
	ExpiresAt    *time.Time
}

// APIKeyStore provides CRUD access to api_keys.
type APIKeyStore struct {
	pool *pgxpool.Pool
}

// NewAPIKeyStore returns an APIKeyStore backed by the given pool.
func NewAPIKeyStore(pool *pgxpool.Pool) *APIKeyStore {
	return &APIKeyStore{pool: pool}
}

// GetByHash fetches an active, non-expired API key by its SHA-256 hex hash.
// Inactive (revoked) or expired keys are treated as missing and return
// ErrNotFound; callers do not have to check IsActive or ExpiresAt themselves.
func (s *APIKeyStore) GetByHash(ctx context.Context, hashHex string) (*APIKey, error) {
	const q = `
		SELECT id, key_hash, key_prefix, org_id, name, scopes,
		       rate_limit_rpm, rate_limit_tpm, is_active,
		       created_at, expires_at, last_used_at
		FROM api_keys
		WHERE key_hash = $1
		  AND is_active = TRUE
		  AND (expires_at IS NULL OR expires_at > NOW())
	`
	row := s.pool.QueryRow(ctx, q, hashHex)
	var k APIKey
	if err := row.Scan(
		&k.ID, &k.KeyHash, &k.KeyPrefix, &k.OrgID, &k.Name, &k.Scopes,
		&k.RateLimitRPM, &k.RateLimitTPM, &k.IsActive,
		&k.CreatedAt, &k.ExpiresAt, &k.LastUsedAt,
	); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("scanning api_key: %w", err)
	}
	return &k, nil
}

// Create persists a new API key. The caller supplies the SHA-256 hex hash
// and the human-readable prefix; the plaintext key never reaches the store.
func (s *APIKeyStore) Create(ctx context.Context, k *NewKey, hashHex, prefix string) (*APIKey, error) {
	const q = `
		INSERT INTO api_keys (key_hash, key_prefix, org_id, name,
		                      rate_limit_rpm, rate_limit_tpm, expires_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		RETURNING id, key_hash, key_prefix, org_id, name, scopes,
		          rate_limit_rpm, rate_limit_tpm, is_active,
		          created_at, expires_at, last_used_at
	`
	row := s.pool.QueryRow(ctx, q,
		hashHex, prefix, k.OrgID, k.Name,
		k.RateLimitRPM, k.RateLimitTPM, k.ExpiresAt,
	)
	var out APIKey
	if err := row.Scan(
		&out.ID, &out.KeyHash, &out.KeyPrefix, &out.OrgID, &out.Name, &out.Scopes,
		&out.RateLimitRPM, &out.RateLimitTPM, &out.IsActive,
		&out.CreatedAt, &out.ExpiresAt, &out.LastUsedAt,
	); err != nil {
		return nil, fmt.Errorf("inserting api_key: %w", err)
	}
	return &out, nil
}

// Revoke marks a key inactive. It is idempotent: revoking an unknown or
// already-revoked id is not an error.
func (s *APIKeyStore) Revoke(ctx context.Context, id string) error {
	const q = `UPDATE api_keys SET is_active = FALSE WHERE id = $1`
	_, err := s.pool.Exec(ctx, q, id)
	if err != nil {
		return fmt.Errorf("revoking api_key: %w", err)
	}
	return nil
}

// GetByID fetches a key (active or not) by id. Used by Revoke flows that
// need the hash to invalidate the cache.
func (s *APIKeyStore) GetByID(ctx context.Context, id string) (*APIKey, error) {
	const q = `
		SELECT id, key_hash, key_prefix, org_id, name, scopes,
		       rate_limit_rpm, rate_limit_tpm, is_active,
		       created_at, expires_at, last_used_at
		FROM api_keys
		WHERE id = $1
	`
	row := s.pool.QueryRow(ctx, q, id)
	var k APIKey
	if err := row.Scan(
		&k.ID, &k.KeyHash, &k.KeyPrefix, &k.OrgID, &k.Name, &k.Scopes,
		&k.RateLimitRPM, &k.RateLimitTPM, &k.IsActive,
		&k.CreatedAt, &k.ExpiresAt, &k.LastUsedAt,
	); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("scanning api_key: %w", err)
	}
	return &k, nil
}

// TouchLastUsedAt updates the last_used_at timestamp to now. Failures are
// returned to the caller; the auth cache invokes this from a debounced
// goroutine and logs failures rather than aborting the request.
func (s *APIKeyStore) TouchLastUsedAt(ctx context.Context, id string) error {
	const q = `UPDATE api_keys SET last_used_at = NOW() WHERE id = $1`
	_, err := s.pool.Exec(ctx, q, id)
	if err != nil {
		return fmt.Errorf("touching api_key: %w", err)
	}
	return nil
}
